
CREATE TABLE IF NOT EXISTS CUSTOMER(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(250) NOT NULL,
  ADDRESS  VARCHAR(250) NOT NULL,
  EMAIL_ADDRESS VARCHAR(50) DEFAULT NULL,
  CONTACT_NUMBER VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS VEHICLE(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  registration_number VARCHAR(250) NOT NULL,
  engine_number  VARCHAR(250) NOT NULL,
  vehicleType VARCHAR(5) NOT NULL,
  CUSTOMER_id INT,
  FOREIGN KEY(CUSTOMER_id) REFERENCES CUSTOMER(id)
);


CREATE TABLE IF NOT EXISTS SERVICE_RECORD(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  vehicleId INT,
  accepted BOOLEAN,
  estimatedCost DOUBLE,
  estimateDeliveryDay DATE,
  service_acceptedDate DATE,
  totalCost DOUBLE,
  serviceCompleted BOOLEAN,
  FOREIGN KEY(vehicleId) REFERENCES VEHICLE(id)
);


